services:
  recipe-search-service:
    image: recipe-search-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe-search-service
    ports:
      - "8000:8000"
    volumes:
      - ./env:/app/env
    restart: unless-stopped

  embedding-service:
    image: semitechnologies/transformers-inference:sentence-transformers-all-mpnet-base-v2-1.9.7
    container_name: embedding-service
    restart: unless-stopped