services:
  recipe-search-service:
    image: recipe-search-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe-search-service
    ports:
      - "8000:8000"
    volumes:
      - ./env:/app/env
    restart: unless-stopped